# 사이트 기본 설정
site_name: nofairTCM | RBLX 탈출맵 프로젝트
site_url: https://qwreey75.github.io/luakrdoc/
site_author: nofair, qwreey, L_02L, ...
site_description: lua 5.3 wiki for korean

# 리포 설정
repo_name: luakrdoc
repo_url: https://github.com/qwreey75/luakrdoc
edit_uri: ""

# 벤치 설정-사이트dir 설정, 저장소 하나로 관리하기 위해서 이렇게 씀
remote_branch: master
docs_dir: docroot
site_dir: docs

# 검색엔진 설정
lang: multi # 한글이 없어서 어쩔 수 없이 묶음으로 사용
min_search_length: 2 # 최소 검색 단위

# 테스팅 사이트 설정(로컬 서버)
dev_addr: '127.0.0.1:8000'

# 추가 Css
extra_css:
    - stylesheets/extra.css

# 다른 설정
#extra:
#  disqus: luakrdoc # 디스커스 설정

# 사이드바
nav:
    - 시작하기: 'index.md'
    - 자료형:
        - 문자열: 'docs/stringvar.md'
    - 라이브러리:
        - 문자열 라이브러리: 'docs/stringlib.md'
    - 기여자: 'acknowledgements.md'

# 테마링
theme:
    # 기본 설정
    name: material
    custom_dir: overrides

    # 테마
    palette:
        scheme: custom #youtube
        #primary: purple
        #accent: deep purple

    # 세부기능 Flag
    features:
        - toc.integrate # 목차를 네비게이션에 합치기
        - navigation.instant # 빠른 페이지 로드

    # 결과 없음 페이지
    static_templates:
      - 404.html

    # 언어/폰트
    language: kr
    font: false
    #font:
    #    text: Roboto
    #    code: Roboto Mono

    # 아이콘
    favicon: assets/LUAICON_TP.png
    logo: assets/LUAICON_DARK.png

    # 일부 설정
    include_search_page: false
    search_index_only: true

plugins:
    - search
    - exclude-search:
        exclude:
            - acknowledgements.md
            - addons.md
    - macros

# Markdown 플러그인
markdown_extensions:
    # 컴포넌트
    - pymdownx.tabbed # 탭
    - admonition # 노트라인
    - pymdownx.details # 더보기(확장 가능한 라벨)
    - pymdownx.progressbar # 프로그래스 바
    - attr_list # ID 붙이기
    - def_list # 기본 리스트

    # 기초 설정
    - footnotes # 바닥글
    - pymdownx.superfences # 스페이스 관현, 펜스 중첩허용
    - pymdownx.keys # 단축키(검색)
    - pymdownx.magiclink # 링크 확장기
    - pymdownx.inlinehilite # 인라인 코드 하이라이팅
    - pymdownx.highlight: # 코드 구문강조
        linenums: true # 코드라인 넘버
    - pymdownx.emoji: # 이모지 불러오기
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.tasklist: # 체크박스 불러오기
          custom_checkbox: true
    - pymdownx.betterem: # 더 나은 글자 서식 알고리즘
          smart_enable: all
    - pymdownx.smartsymbols: # 특수문자 쉬운입력
        fractions: false
    - markdown_include.include: # 다른 md 파일 가져와서 보여주기
        base_path: docroot

    # 기타 세부 설정
    - codehilite: # 코드 언어 추측 끄기
          guess_lang: false
    - toc: # 부분 링크 허용
          permalink: true
    - meta # 메타데이터 관련
    
    # 사용되지 않는 플러그인
    #- pymdownx.snippets # 외부 md 로더
    #- pymdownx.tilde #아래첨자 단순화
    #- pymdownx.arithmatex # 수학적 표현 표시
    #- pymdownx.caret # ^ 기호로 글자 서식 추가
    #- pymdownx.critic # 내용추가,제거,비평 하이라이터
    #- pymdownx.b64 # base64 로 이미지를 html에 임베드
    #- pymdownx.escapeall # 모든 이스캐이프 허용
    #- abbr # 줄임말 표현 세부정보 붇이기
    #- pymdownx.mark # 마킹(형광마커 효과)